path: "/home/lixion/rgbd/ultra/ultralytics_rgbd/ultralytics/assets/"

train: ["images", "lidar_d"]
val: ["images", "lidar_d"]

channels: 4

names:
    0: person
    1: bicycle
    2: car
    3: don't care